// Generated by CoffeeScript 1.7.1

/*
    Author: Dalston Xu
    Updated: 2014年4月9日1:02:49
 */

(function() {
  var getLocation, getWeatherByCityName, getWeatherByGeoCoords, run, updateWeatherInfo;

  document.addEventListener('DOMContentLoaded', function() {
    var audioSpan;
    run();
    audioSpan = 7288;
    soundManager.setup({
      onready: function() {
        var rain1, rain2, t;
        rain1 = soundManager.createSound({
          id: 'rain1',
          url: 'audio/rainfade_1.mp3',
          autoLoad: true,
          multiShotEvents: true,
          onload: function() {
            return this.play({
              position: 0
            });
          },
          onfinish: function() {
            return this.play({
              position: 0
            });
          }
        });
        rain1.play();
        t = false;
        rain2 = soundManager.createSound({
          id: 'rain2',
          url: 'audio/rainfade_1.mp3',
          autoLoad: true,
          multiShotEvents: true,
          onload: function() {
            return this.play({
              volume: 0,
              position: audioSpan
            });
          },
          onfinish: function() {
            return this.play({
              position: 0
            });
          },
          onplay: function() {
            var e, i, n, r;
            if (t) {
              return false;
            }
            e = 3 * 1e3;
            n = 0;
            r = 100;
            return i = setInterval(function() {
              rain2.setVolume((1 + n) * (r / 12));
              n++;
              if (n === 12) {
                clearInterval(i);
                return t = true;
              }
            }, e / 12);
          }
        });
        return rain2.play();
      }
    });
    return getLocation();
  });

  run = function() {
    var image;
    image = document.getElementById('background');
    image.onload = function() {
      var engine;
      engine = new RainyDay({
        image: this,
        gravityAngle: Math.PI / 9
      });
      engine.trail = engine.TRAIL_SMUDGE;
      return engine.rain([[1, 0, 100], [3, 3, 1], [1, 4, 20]], 100);
    };
    image.crossOrigin = 'anonymous';
    return image.src = './images/shanghai.jpg';
  };

  getLocation = function() {
    var error, success;
    success = function(position) {
      $("#aside").addClass("show");
      $("#geo_info").text(position);
      return getWeatherByGeoCoords([position.coords.latitude, position.coords.longtitude]);
    };
    error = function(error) {
      switch (error.code) {
        case error.PERMISSION_DENIED:
          console.info("PERMISSION_DENIED");
          break;
        case error.POSITION_UNAVAILABLE:
          console.info("POSITION_UNAVAILABLE");
          break;
        case error.TIMEOUT:
          console.info("TIMEOUT");
          break;
        case error.UNKNOWN_ERROR:
          console.info("UNKNOWN_ERROR");
      }
      return $.get("http://ipinfo.io", function(response) {
        var coords;
        $("#aside").addClass("show");
        coords = response.loc.split(",");
        if (response.city !== null) {
          $("#geo_info").text(response.city);
          return getWeatherByCityName(response.city);
        } else {
          $("#geo_info").text(response.loc);
          return getWeatherByGeoCoords(coords[0], coords[1]);
        }
      }, "jsonp");
    };
    return navigator.geolocation.getCurrentPosition(success, error);
  };

  getWeatherByCityName = function(cityName) {
    return $.get("http://api.openweathermap.org/data/2.5/weather?q=" + cityName + "&APPID=cb44c4f3d297066b575ecf0bf5dd0751 ", function(response) {
      return updateWeatherInfo(response);
    }, "jsonp");
  };

  getWeatherByGeoCoords = function(lat, lon) {
    return $.get("http://api.openweathermap.org/data/2.5/weather?lat=" + lat + "&lon=" + lon + "&APPID=cb44c4f3d297066b575ecf0bf5dd0751 ", function(response) {
      return updateWeatherInfo(response);
    }, "jsonp");
  };

  updateWeatherInfo = function(weatherInfo) {
    var weather_icon, weather_main, weather_temp;
    weather_main = weatherInfo.weather[0].main;
    weather_icon = weatherInfo.weather[0].icon;
    weather_temp = weatherInfo.main.temp;
    $("#weather_icon").attr({
      "src": "http://openweathermap.org/img/w/" + weather_icon + ".png",
      "title": weather_main,
      "alt": weather_main
    });
    $("#aside").addClass(weather_main);
    $("#weather_text").text(weather_main);
    return $("#weather_temp").text(weather_temp + " °F");
  };

}).call(this);
